language: rust
branches:
  only:
    - master
os:
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work, but don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry
cache:
  directories:
    - /home/travis/.cargo
before_script:
  - if [[ "$TRAVIS_RUST_VERSION" == "stable" || "$TRAVIS_RUST_VERSION" == "nightly" ]]; then rustup component add clippy-preview; fi
  - rustup component add rustfmt
script:
  - if [[ "$TRAVIS_RUST_VERSION" == "stable" || "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo clippy --all-targets --all-features -- -D warnings; fi
  - cargo fmt --all --write-mode diff
  - cargo build
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
