language: rust
os:
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
# Cache dependencies so that they are only recompiled
# if they or the compiler were upgraded
cache: cargo
before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
