[package]
name = "supernova"
version = "0.1.0"
authors = ["0xazure <stuart.crust@gmail.com>"]

[dependencies]
reqwest = "0.8.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
clippy = "0.0.302"
